/*
 * generated by Xtext 2.10.0
 */
package de.imotep.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimpleFeatureExpressionScopeProvider extends DelegatingScopeProvider {
}
