<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mm"
    nsURI="http://mm/1.0" nsPrefix="mm">
  <eClassifiers xsi:type="ecore:EClass" name="Child"/>
  <eClassifiers xsi:type="ecore:EClass" name="P1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c1" eType="#//Child" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c2" upperBound="-1" eType="#//Child"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c3" lowerBound="1" eType="#//Child"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
