/*
 * generated by Xtext 2.10.0
 */
package de.imotep.parser.antlr;

import com.google.inject.Inject;
import de.imotep.parser.antlr.internal.InternalSimpleFeatureExpressionParser;
import de.imotep.services.SimpleFeatureExpressionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimpleFeatureExpressionParser extends AbstractAntlrParser {

	@Inject
	private SimpleFeatureExpressionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleFeatureExpressionParser createParser(XtextTokenStream stream) {
		return new InternalSimpleFeatureExpressionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SimpleFeatureExpression";
	}

	public SimpleFeatureExpressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleFeatureExpressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
