/*
 * generated by Xtext 2.10.0
 */
package de.imotep.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimpleFeatureExpressionAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/imotep/parser/antlr/internal/InternalSimpleFeatureExpression.tokens");
	}
}
