/**
 * generated by Xtext 2.10.0
 */
package de.imotep.simpleFeatureExpression.impl;

import de.imotep.simpleFeatureExpression.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SimpleFeatureExpressionFactoryImpl extends EFactoryImpl implements SimpleFeatureExpressionFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SimpleFeatureExpressionFactory init()
  {
    try
    {
      SimpleFeatureExpressionFactory theSimpleFeatureExpressionFactory = (SimpleFeatureExpressionFactory)EPackage.Registry.INSTANCE.getEFactory(SimpleFeatureExpressionPackage.eNS_URI);
      if (theSimpleFeatureExpressionFactory != null)
      {
        return theSimpleFeatureExpressionFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SimpleFeatureExpressionFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleFeatureExpressionFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SimpleFeatureExpressionPackage.SIMPLE_FEATURE_EXPRESSION: return createSimpleFeatureExpression();
      case SimpleFeatureExpressionPackage.BRACED_EXPRESSION: return createBracedExpression();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleFeatureExpression createSimpleFeatureExpression()
  {
    SimpleFeatureExpressionImpl simpleFeatureExpression = new SimpleFeatureExpressionImpl();
    return simpleFeatureExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BracedExpression createBracedExpression()
  {
    BracedExpressionImpl bracedExpression = new BracedExpressionImpl();
    return bracedExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimpleFeatureExpressionPackage getSimpleFeatureExpressionPackage()
  {
    return (SimpleFeatureExpressionPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SimpleFeatureExpressionPackage getPackage()
  {
    return SimpleFeatureExpressionPackage.eINSTANCE;
  }

} //SimpleFeatureExpressionFactoryImpl
