/**
 * generated by Xtext 2.10.0
 */
package de.imotep.simpleFeatureExpression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Braced Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.imotep.simpleFeatureExpression.BracedExpression#getExpr1 <em>Expr1</em>}</li>
 *   <li>{@link de.imotep.simpleFeatureExpression.BracedExpression#getOp <em>Op</em>}</li>
 *   <li>{@link de.imotep.simpleFeatureExpression.BracedExpression#getExpr2 <em>Expr2</em>}</li>
 * </ul>
 *
 * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionPackage#getBracedExpression()
 * @model
 * @generated
 */
public interface BracedExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr1</em>' containment reference.
   * @see #setExpr1(SimpleFeatureExpression)
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionPackage#getBracedExpression_Expr1()
   * @model containment="true"
   * @generated
   */
  SimpleFeatureExpression getExpr1();

  /**
   * Sets the value of the '{@link de.imotep.simpleFeatureExpression.BracedExpression#getExpr1 <em>Expr1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr1</em>' containment reference.
   * @see #getExpr1()
   * @generated
   */
  void setExpr1(SimpleFeatureExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionPackage#getBracedExpression_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

  /**
   * Returns the value of the '<em><b>Expr2</b></em>' containment reference list.
   * The list contents are of type {@link de.imotep.simpleFeatureExpression.SimpleFeatureExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' containment reference list.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionPackage#getBracedExpression_Expr2()
   * @model containment="true"
   * @generated
   */
  EList<SimpleFeatureExpression> getExpr2();

} // BracedExpression
