/**
 * generated by Xtext 2.10.0
 */
package de.imotep.simpleFeatureExpression;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionFactory
 * @model kind="package"
 * @generated
 */
public interface SimpleFeatureExpressionPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simpleFeatureExpression";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imotep.de/SimpleFeatureExpression";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simpleFeatureExpression";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleFeatureExpressionPackage eINSTANCE = de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionPackageImpl.init();

  /**
   * The meta object id for the '{@link de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionImpl <em>Simple Feature Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionImpl
   * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionPackageImpl#getSimpleFeatureExpression()
   * @generated
   */
  int SIMPLE_FEATURE_EXPRESSION = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_EXPRESSION__VAR = 0;

  /**
   * The feature id for the '<em><b>Neg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_EXPRESSION__NEG = 1;

  /**
   * The feature id for the '<em><b>Bra Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_EXPRESSION__BRA_EXPR = 2;

  /**
   * The number of structural features of the '<em>Simple Feature Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.imotep.simpleFeatureExpression.impl.BracedExpressionImpl <em>Braced Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.imotep.simpleFeatureExpression.impl.BracedExpressionImpl
   * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionPackageImpl#getBracedExpression()
   * @generated
   */
  int BRACED_EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Expr1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRACED_EXPRESSION__EXPR1 = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRACED_EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Expr2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRACED_EXPRESSION__EXPR2 = 2;

  /**
   * The number of structural features of the '<em>Braced Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRACED_EXPRESSION_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link de.imotep.simpleFeatureExpression.SimpleFeatureExpression <em>Simple Feature Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Feature Expression</em>'.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpression
   * @generated
   */
  EClass getSimpleFeatureExpression();

  /**
   * Returns the meta object for the attribute '{@link de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getVar()
   * @see #getSimpleFeatureExpression()
   * @generated
   */
  EAttribute getSimpleFeatureExpression_Var();

  /**
   * Returns the meta object for the attribute '{@link de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getNeg <em>Neg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Neg</em>'.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getNeg()
   * @see #getSimpleFeatureExpression()
   * @generated
   */
  EAttribute getSimpleFeatureExpression_Neg();

  /**
   * Returns the meta object for the containment reference '{@link de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getBraExpr <em>Bra Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bra Expr</em>'.
   * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpression#getBraExpr()
   * @see #getSimpleFeatureExpression()
   * @generated
   */
  EReference getSimpleFeatureExpression_BraExpr();

  /**
   * Returns the meta object for class '{@link de.imotep.simpleFeatureExpression.BracedExpression <em>Braced Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Braced Expression</em>'.
   * @see de.imotep.simpleFeatureExpression.BracedExpression
   * @generated
   */
  EClass getBracedExpression();

  /**
   * Returns the meta object for the containment reference '{@link de.imotep.simpleFeatureExpression.BracedExpression#getExpr1 <em>Expr1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr1</em>'.
   * @see de.imotep.simpleFeatureExpression.BracedExpression#getExpr1()
   * @see #getBracedExpression()
   * @generated
   */
  EReference getBracedExpression_Expr1();

  /**
   * Returns the meta object for the attribute list '{@link de.imotep.simpleFeatureExpression.BracedExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Op</em>'.
   * @see de.imotep.simpleFeatureExpression.BracedExpression#getOp()
   * @see #getBracedExpression()
   * @generated
   */
  EAttribute getBracedExpression_Op();

  /**
   * Returns the meta object for the containment reference list '{@link de.imotep.simpleFeatureExpression.BracedExpression#getExpr2 <em>Expr2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr2</em>'.
   * @see de.imotep.simpleFeatureExpression.BracedExpression#getExpr2()
   * @see #getBracedExpression()
   * @generated
   */
  EReference getBracedExpression_Expr2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimpleFeatureExpressionFactory getSimpleFeatureExpressionFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionImpl <em>Simple Feature Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionImpl
     * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionPackageImpl#getSimpleFeatureExpression()
     * @generated
     */
    EClass SIMPLE_FEATURE_EXPRESSION = eINSTANCE.getSimpleFeatureExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FEATURE_EXPRESSION__VAR = eINSTANCE.getSimpleFeatureExpression_Var();

    /**
     * The meta object literal for the '<em><b>Neg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_FEATURE_EXPRESSION__NEG = eINSTANCE.getSimpleFeatureExpression_Neg();

    /**
     * The meta object literal for the '<em><b>Bra Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_FEATURE_EXPRESSION__BRA_EXPR = eINSTANCE.getSimpleFeatureExpression_BraExpr();

    /**
     * The meta object literal for the '{@link de.imotep.simpleFeatureExpression.impl.BracedExpressionImpl <em>Braced Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.imotep.simpleFeatureExpression.impl.BracedExpressionImpl
     * @see de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionPackageImpl#getBracedExpression()
     * @generated
     */
    EClass BRACED_EXPRESSION = eINSTANCE.getBracedExpression();

    /**
     * The meta object literal for the '<em><b>Expr1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BRACED_EXPRESSION__EXPR1 = eINSTANCE.getBracedExpression_Expr1();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BRACED_EXPRESSION__OP = eINSTANCE.getBracedExpression_Op();

    /**
     * The meta object literal for the '<em><b>Expr2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BRACED_EXPRESSION__EXPR2 = eINSTANCE.getBracedExpression_Expr2();

  }

} //SimpleFeatureExpressionPackage
