/**
 * generated by Xtext 2.10.0
 */
package de.imotep.simpleFeatureExpression;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.imotep.simpleFeatureExpression.SimpleFeatureExpressionPackage
 * @generated
 */
public interface SimpleFeatureExpressionFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpleFeatureExpressionFactory eINSTANCE = de.imotep.simpleFeatureExpression.impl.SimpleFeatureExpressionFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Simple Feature Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Feature Expression</em>'.
   * @generated
   */
  SimpleFeatureExpression createSimpleFeatureExpression();

  /**
   * Returns a new object of class '<em>Braced Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Braced Expression</em>'.
   * @generated
   */
  BracedExpression createBracedExpression();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SimpleFeatureExpressionPackage getSimpleFeatureExpressionPackage();

} //SimpleFeatureExpressionFactory
