/*
 * generated by Xtext 2.10.0
 */
package de.imotep


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimpleFeatureExpressionStandaloneSetup extends SimpleFeatureExpressionStandaloneSetupGenerated {

	def static void doSetup() {
		new SimpleFeatureExpressionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
